### ISSUE TITLE
Letting you know about similar efforts

### ISSUE THREAD

**Issue by nugend** [shystruk/csv-file-validator#1]
Hi there,

Not really an issue or criticism, but thought you might find the British National Archive CSV validation effort worth knowing about: https://github.com/digital-preservation/csv-validator and https://github.com/digital-preservation/csv-schema

**Comment by shystruk** [comment]
Hi @nugend ,

Thank you for letting me know about that. 
I checked and see that British National ... works on Java Virtual Machine (The source code is built using the Apache Maven build tool, by executing mvn clean install). So, its a desktop tool :)

csv-file-validator based on JavaScript and the main uses is Web. Sorry, I have not mentioned that in README

Thank,
Vasyl

**Comment by nugend** [comment]
I'm aware. The point was more along the lines of features you may find interesting and to highlight the efforts in defining a schema format. As I said, not an issue or criticism.

**Comment by shystruk** [comment]
I got your point :)
Thank you for sharing and being interested 👍
