### ISSUE TITLE
Dynamic Typing in PapaParse config breaks the module

### ISSUE THREAD

**Issue by nholmes3** [shystruk/csv-file-validator#103]
Hello,

I noticed an issue with this package where if you pass `parserConfig: { dynamicTyping: true }` in the `config` the code breaks if there are types other than strings in the CSV file (in my case there are numbers).

The module [tries to call `_clearValue`](https://github.com/shystruk/csv-file-validator/blob/master/src/csv-file-validator.js#L200)  which fails because the replace function does not exist on numbers.

The use case is that I want to be able to validate that values in certain columns are in fact numbers. The workaround for now would be to add a validation function to see if the string is numeric:

```
function isNumeric(value: any) {
  return !isNaN(parseFloat(value)) && isFinite(value);
}
```

However, it would be much preferred if we could rely on papaparse to perform the dynamicTyping correctly. Let me know if I can help resolve this. Thanks!

**Comment by shystruk** [comment]
Hey @nholmes3,
Thanks for submitting this. 
If you want to contribute you can create a pull request with a change or I will fix this next week.
