### ISSUE TITLE
Validator is not identifying empty entry in the csv file therefore no error is returned while validation process

### ISSUE THREAD

**Issue by rajatsehgal2010** [shystruk/csv-file-validator#11]
`headers: [
        { 
            name: 'First Name',
            inputName: 'FirstName*',
            required: true,
            requiredError: function (headerName, rowNumber, columnNumber) {
                return '${headerName} is required in the ${rowNumber} row / ${columnNumber} column'
            }
        }`

this is one of the configuration of the header

**Comment by shystruk** [comment]
please check your file here https://github.com/shystruk/create-react-redux-app-structure page CSV Validator. Validator gets each .csv file row and then get config from headers per index and validate data, so do not skip config headers.
