### ISSUE TITLE
Add configuration option for converting CSV column number indices to letter indices for validation

### ISSUE THREAD

**Issue by lulzash** [shystruk/csv-file-validator#110]
Request the addition of a configuration option to allow for the conversion of CSV column number indices to letter indices for validation purposes. Currently, when validating CSV files, it is necessary to manually convert column number indices to letter indices in order to accurately identify and reference specific columns. This can be time-consuming and error-prone, especially when working with large CSV files.

Adding a configuration option to automatically convert column number indices to letter indices would greatly improve the efficiency and accuracy of CSV validation processes. It would also make it easier for users to understand and reference specific columns within a CSV file.

Currently, it is not possible to convert CSV column numbers to letters using the current configuration options. This can be inconvenient when working with large CSV files, as it is difficult to read and understand the data when the columns are represented by numbers.

I propose adding a new configuration option that allows users to specify whether or not to convert column numbers to letters. 

I envision this configuration option being a boolean flag, with a default value of "false". When set to "true", the column numbers in the CSV file would be automatically converted to letters.

**Comment by shystruk** [comment]
@lulzash please share some examples and a CSV file

**Comment by lulzash** [comment]
@shystruk  Sure, I can provide some examples using the same CSV file in the demo folder to help illustrate the need for this feature.

For example, consider a CSV file with the following columns: "A", "B", "C", "D", "E". 

![CSV-Viewer-and-Editor](https://user-images.githubusercontent.com/28122609/213418637-603d5762-7d66-4ef4-92b2-cf944af33de1.jpg)

which throws validations

![CSV-File-Validator-Demo](https://user-images.githubusercontent.com/28122609/213418830-d5828c79-c5d8-4851-99cf-6479273ab134.jpg)


For first validation, If a user needs to reference column "D" in their validation process, they would currently need to manually convert the column number (4) to the letter "D". However, if the proposed configuration option was set to "true", the user would not need to manually convert the column number and could simply reference "D" directly. 

When configuration is enable these same validation will look like

![after validation](https://user-images.githubusercontent.com/28122609/213420894-174240a7-a94a-41ee-a516-c707fc37e23f.jpg)


**I would like to add that while it may be easy for a user to manually convert column numbers to letters for small CSV files, it becomes increasingly difficult and time-consuming as the number of columns increases. For example, in a large CSV file with hundreds of columns, manually converting column numbers to letters could be a tedious and error-prone process. This is where the proposed configuration option would greatly improve the efficiency and accuracy of CSV validation processes.**
