### ISSUE TITLE
TypeError: (0 , csv_file_validator_1.default) is not a function

### ISSUE THREAD

**Issue by Sheikh566** [shystruk/csv-file-validator#113]
```
import CSVFileValidator from "csv-file-validator";

.
.
.
public async ValidateCsv(csv: string, validation) {
  const data = await CSVFileValidator(csv, validation);

  return { data };
}
.
.
.
```

I am using node v14.20.1 and npm 6.14.17

I don't know why I am getting this error: TypeError: (0 , csv_file_validator_1.default) is not a function

**Comment by Sheikh566** [comment]
I used `const CSVFileValidator = require("csv-file-validator");` instead of above import to make it work.

**Comment by shystruk** [comment]
@Sheikh566 thanks for submitting the issue. I'll check

**Comment by shystruk** [comment]
hm, can't reproduce that. If you are using TS try to add this to your config file `esModuleInterop`
https://www.typescriptlang.org/tsconfig#esModuleInterop
