### ISSUE TITLE
How can we validate headers, not values? and optional key is not working, showing same result for both boolean values.

### ISSUE THREAD

**Issue by rajatsehgal2010** [shystruk/csv-file-validator#12]

**Comment by shystruk** [comment]
@rajatsehgal2010 can you please share config

**Comment by shystruk** [comment]
@rajatsehgal2010 optional makes column optional. If true column value will be return

**Comment by shystruk** [comment]
use the latest version for header validation. headerError function will be called when the header is not valid :)
csv-file-validator@1.6.0
