### ISSUE TITLE
Number of fields check for the first row

### ISSUE THREAD

**Issue by mzbortek** [shystruk/csv-file-validator#123]
I think this check needs to be done also for the first row of CSV file.

So, instead of this:
```
			// fields are mismatch
			if (rowIndex !== 0 && row.length !== config.headers.length) {
```
should be this:
```
			// fields are mismatch
			if (row.length !== config.headers.length) {
```

**Comment by shystruk** [comment]
we always assume the presence of a .csv file with header names in the first row, and we do not validate if the number of fields mismatches the headers.
