### ISSUE TITLE
Is it possible to require at least one (any) of a span of columns?

### ISSUE THREAD

**Issue by brandondurham** [shystruk/csv-file-validator#18]
I have a CSV template that includes 20 headers. Five of those are required, and then there is a span of 12 that are all individually optional, but at least one must have value and pass validation.

Is this inherently possible with csv-file-validator? Would you have a recommended way to pull it off if not?

**Comment by shystruk** [comment]
@brandondurham not possible to do kind of validation now. What you can do is to get a response and see if one of the optional header passing a validation.

**Comment by shystruk** [comment]
Obsolete. No plans to support a kind of validation.
