### ISSUE TITLE
Allow parsing options to be given when validating a CSV

### ISSUE THREAD

**Issue by Liiva** [shystruk/csv-file-validator#34]
My use case is that users often provide CSV files with a trailing newline and this library considers that to be an invalid file if any of the headers is required. I'd like to simply skip these lines and PapaParse has an option for this in `skipEmptyLines: true`, however the current structure has no way for me to pass this option to the internal PapaParse instance.

I've currently [forked this repo and added a commit](https://github.com/CuriousInc/csv-file-validator/commit/68eb87a64cc18154f5207f405732c1f1421d6543) to fix above issue by allowing a third "options" argument to be given to the validator. If you like this approach then I can create a pull request for it.

**Comment by shystruk** [comment]
@Liiva Good point. I would like to see and merge your pull request. Thanks!

**Comment by Liiva** [comment]
Just a small update: I'm having some issues reproducing this case in the unit tests, which is holding me back from submitting the pull request. I still intend on doing this but time is short...

**Comment by shystruk** [comment]
@Liiva thanks for the update. Take your time :)

**Comment by shystruk** [comment]
Hi @Liiva,
By default `skipEmptyLines: true` is passing to PapaParse.
Currently, no other configs are supported. If you need some please create a new issue.
