### ISSUE TITLE
Not able to define optional columns

### ISSUE THREAD

**Issue by ganeshpatro321** [shystruk/csv-file-validator#6]
Is there a way to define optional columns @shystruk

**Comment by shystruk** [comment]
@ganeshpatro321 
What do you mean by optional? 
You can skip the required check and any type of validation.

**Comment by ganeshpatro321** [comment]
For example, 

there is a column that may be there in the file or maynot be, if the column is there then I need it, but if not it should not cause any issue

In the current version of your code, 

If I define the headers in the config, and if that particular header is not there in the file, then it returns no objects, 


I need a way so that the columns may also be optional

**Comment by shystruk** [comment]
@ganeshpatro321 
please add config and file headers example, and what you expected to see as result

**Comment by ganeshpatro321** [comment]
So,

Config has [ x, y, z, a, b]
and file has headers as [x, y, z]

What happens is it doesnt return any objects,

What my requirement is it returns the objects and consider a and b as optional columns
@shystruk
