### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by javierlinked** [shystruk/csv-file-validator#64]
Hello, 

I'd needed to add type definitions for this package, as I am using it from TypeScript project.

Can I prepare a PR and include them in the package?

**Comment by shystruk** [comment]
Hi @javierlinked,
You are welcome to do that :)
Thanks

**Comment by javierlinked** [comment]
Done.

**Comment by javierlinked** [comment]
I don't find an option for assigning you as reviewer. 
Here you are. https://github.com/shystruk/csv-file-validator/pull/66
