### ISSUE TITLE
In uniqueError function, getting the rowNumber as undefined

### ISSUE THREAD

**Issue by ramprakash74** [shystruk/csv-file-validator#88]
Hi, I am trying to get the rowNumber for the unique error, but i am getting it as undefined.
{
      name: 'Employee ID (ZID)',
      inputName: 'EmployeeID ',
      required: false,
      unique: true,
      uniqueError: function (headerName, rowNumber) {
        return `${headerName} is not unique at the ${rowNumber} row`
      },
    },

![image](https://user-images.githubusercontent.com/94838961/142853224-d70a2596-6e11-4077-b939-287c5a458321.png)

**Comment by shystruk** [comment]
@ramprakash74 can you please share some test .csv file

**Comment by ramprakash74** [comment]
@shystruk Attaching the csv file i am using
[TI-GWS-061.csv](https://github.com/shystruk/csv-file-validator/files/7585928/TI-GWS-061.csv)

**Comment by ramprakash74** [comment]
@shystruk Hi..are you able to recreate the issue with the test file i sent? thanks

**Comment by shystruk** [comment]
@ramprakash74 please share a config too

**Comment by ramprakash74** [comment]
@shystruk below is the config
export const CSVconfig = {
  headers: [
    {
      name: 'Space ID',
      inputName: 'SpaceID',
      required: true,
      requiredError: function (headerName, rowNumber, columnNumber) {
        return `${headerName} is required in column ${columnNumber}/row ${rowNumber}`
      },
    },
    {
      name: 'Space Category',
      inputName: 'SpaceCategory',
      required: true,
      requiredError: function (headerName, rowNumber, columnNumber) {
        return `${headerName} is required in column ${columnNumber}/row ${rowNumber}`
      },
    },
    {
      name: 'Space Type',
      inputName: 'SpaceType',
      required: true,
      requiredError: function (headerName, rowNumber, columnNumber) {
        return `${headerName} is required in column ${columnNumber}/row ${rowNumber}`
      },
    },
    {
      name: 'Space Status',
      inputName: 'SpaceStatus',
      required: true,
      requiredError: function (headerName, rowNumber, columnNumber) {
        return `${headerName} is required in column ${columnNumber}/row ${rowNumber}`
      },
    },
    {
      name: 'Building ID',
      inputName: 'BuildingID',
      required: true,
      requiredError: function (headerName, rowNumber, columnNumber) {
        return `${headerName} is required in column ${columnNumber}/row ${rowNumber}`
      },
    },
    {
      name: 'Floor ID',
      inputName: 'FloorID',
      required: true,
      requiredError: function (headerName, rowNumber, columnNumber) {
        return `${headerName} is required in column ${columnNumber}/row ${rowNumber}`
      },
    },
    {
      name: 'Assigned to (Full Name)',
      inputName: 'Assignedto',
      required: false,
    },
    {
      name: 'Employee ID (ZID)',
      inputName: 'EmployeeID ',
      required: false,
      unique: true,
      uniqueError: function (headerName, rowNumber) {
        return `${headerName} is not unique at the ${rowNumber} row`
      },
    },
    {
      name: 'Manager Name',
      inputName: 'ManagerName',
      required: false,
    },
    {
      name: 'Pyramid',
      inputName: 'Pyramid',
      required: false,
    },
  ],
}

**Comment by shystruk** [comment]
@ramprakash74 works well for me and return row numbers. Please check the .csv file which you get. The headers configurations are ok.


<img width="983" alt="Screen Shot 2021-12-01 at 9 43 57 PM" src="https://user-images.githubusercontent.com/5999543/144364990-babfc49d-a700-441b-96be-d41dec9c2275.png">

**Comment by shystruk** [comment]
please reopen if you still have an issue with that

**Comment by ramprakash74** [comment]
@shystruk Thank you. it works now. how to ignore blanks while checking uniqueness?
