### ISSUE TITLE
I got UndetectableDelimiter as in csv file i am using , the delimiter is "," . So how can I add delimiter?

### ISSUE THREAD

**Issue by rajatsehgal2010** [shystruk/csv-file-validator#9]
`errors: 
    [ { type: 'Delimiter',
       code: 'UndetectableDelimiter',
        message: 'Unable to auto-detect delimiting character; defaulted to \',\'',
        row: undefined } ],
   meta: 
    { delimiter: ',',
      linebreak: '\n',     
      aborted: false,
      truncated: false,
      cursor: 105 } `

**Comment by shystruk** [comment]
Can you please attach the .csv file and config

**Comment by rajatsehgal2010** [comment]
[TechCrunchcontinentalUSA.csv.zip](https://github.com/shystruk/csv-file-validator/files/3166468/TechCrunchcontinentalUSA.csv.zip)

	```
const config = {
    headers: []
}
```

**Comment by shystruk** [comment]
@rajatsehgal2010 for now please use ";" delimiter. example https://github.com/shystruk/csv-file-validator/blob/master/demo/demo.csv
You can export .csv file and choose which delimiter you want to see. some link for help https://optimalbi.com/blog/2015/07/16/how-to-export-an-excel-file-to-pipe-delimited-file-rather-than-comma-delimited-file/

**Comment by shystruk** [comment]
@rajatsehgal2010 your file is valid, check here - https://www.papaparse.com/demo
delimiter is auto-detect. You can check csv validator package here - https://github.com/shystruk/create-react-redux-app-structure, latest version.
