### ISSUE TITLE
[Bug] Using Papaparse config header = true

### ISSUE THREAD

**Issue by Mitchnsun** [shystruk/csv-file-validator#93]
If we set the property `header` in the config for papaparse. CSV File Validator cannot parse file

Error: `csv-file-validator.js:62 Uncaught TypeError: row.forEach is not a function at csv-file-validator.js:62`

**Comment by shystruk** [comment]
The validator does not support `header` option in papaparse config. 
Please see the .csv file example. The first row is a header and the next is a body that will be validated. 
https://github.com/shystruk/csv-file-validator/blob/master/demo/demo.csv
